# -*- coding: utf-8 -*-
"""
Generate Tosca .par parameter file for Experiment 5 topology optimization.

Writes the .par file directly (bypasses writeParAndInputFiles() which has
a KeyError bug in Abaqus 2025). The .par format is based on Tosca examples
in $ABAQUS_HOME/SMATsoResources/abaqus/examples/topo/.
"""

import os

try:
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    SCRIPT_DIR = os.path.join(os.getcwd(), 'scripts')
PROJECT_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, os.pardir))

MESH_SIZE = float(os.environ.get('ABAQUS_MESH_SIZE', '3.0'))
MAX_CYCLES = int(os.environ.get('ABAQUS_MAX_CYCLES', '50'))

PAR_CONTENT = """\
! Experiment 5: Topology Optimization Parameter File
! Generated by generate_par_file.py
!
! Objective: Minimize strain energy (maximize stiffness)
! Constraint: Volume <= 40% of original
! Method: SIMP (penalty 3.0)
! Frozen regions: 3 pin hole areas

FEM_INPUT
  ID_NAME                = MY_INPUT_FILES
  FILE                   = Experiment5_FEA_flat.inp
END_

! ---------- Design Responses ----------

DRESP
  ID_NAME                = DRESP_STRAIN_ENERGY
  DEF_TYPE               = SYSTEM
  TYPE                   = STRAIN_ENERGY
  EL_GROUP               = AllCells
  GROUP_OPER             = SUM
END_

DRESP
  ID_NAME                = DRESP_VOLUME
  DEF_TYPE               = SYSTEM
  TYPE                   = VOLUME
  EL_GROUP               = AllCells
  GROUP_OPER             = SUM
END_

! ---------- Objective Function ----------

OBJ_FUNC
  ID_NAME                = MIN_STRAIN_ENERGY
  TARGET                 = MIN
  DRESP                  = DRESP_STRAIN_ENERGY
END_

! ---------- Constraints ----------

CONSTRAINT
  ID_NAME                = VOLUME_CONSTRAINT
  DRESP                  = DRESP_VOLUME
  MAGNITUDE              = REL
  LE_VALUE               = 0.4
END_

! ---------- Design Variables ----------

DV_TOPO
  ID_NAME                = DESIGN_AREA
  EL_GROUP               = AllCells
END_

! ---------- Frozen Regions ----------

GROUP_DEF
  ID_NAME                = ALL_FROZEN
  TYPE                   = ELEM
  FORMAT                 = LIST_GROUP
LIST_BEGIN
FreezeUpperPin, FreezeLowerLeft, FreezeLowerRight
END_

DVCON_TOPO
  ID_NAME                = FROZEN_PINS
  CHECK_TYPE             = FROZEN
  EL_GROUP               = ALL_FROZEN
END_

! ---------- Optimization Task ----------

OPTIMIZE
  ID_NAME                = TOPOLOGY_OPTIMIZATION
  DV                     = DESIGN_AREA
  OBJ_FUNC               = MIN_STRAIN_ENERGY
  CONSTRAINT             = VOLUME_CONSTRAINT
  DVCON                  = FROZEN_PINS
  STRATEGY               = TOPO_SENSITIVITY
END_

OPT_PARAM
  ID_NAME                = OPT_PARAMS
  OPTIMIZE               = TOPOLOGY_OPTIMIZATION
  MAT_INTERPOLATION      = SIMP
  TOPO_FILTER_RADIUS     = {filter_radius}
END_

STOP
  ID_NAME                = GLOBAL_STOP
  ITER_MAX               = {max_cycles}
END_

SMOOTH
  ID_NAME                = ISO_SMOOTHING
  TASK                   = iso
  ISO_VALUE              = 0.3
  SELF_INTERSECTION_CHECK = runtime
  SMOOTH_CYCLES          = 10
  REDUCTION_RATE         = 60
  REDUCTION_ANGLE        = 5.0
  FORMAT                 = stl
END_
""".format(
    filter_radius=MESH_SIZE * 2.0,
    max_cycles=MAX_CYCLES,
)

par_path = os.path.join(PROJECT_DIR, 'Experiment5_TO.par')
with open(par_path, 'w') as f:
    f.write(PAR_CONTENT)

print("Generated: {}".format(par_path))
print("  Filter radius: {} mm".format(MESH_SIZE * 2.0))
print("  Max cycles: {}".format(MAX_CYCLES))
